### ISSUE TITLE
Contact me please

### ISSUE THREAD

**Issue by LionisIAm** [funtax/airaudio-magisk-module#1]
Hi. Sorry me writting here. 
Didnt find any contancts to find you.
Please answer if you have any information about AirPlayAuth BUT on AppleTV side. Maybe you are thinkg about to develop one more lib as your AirPlayAuth but receiver part.

**Comment by funtax** [comment]
Hey @LionisIAm ,

I have sadly not worked on the ATV-side of the authentication.
Furthermore, I did not reverse-engineered the authentication itself but decompiled & reverse-engineered another, closed-source project that has been updated with the authentication of the user side.

The only project that seems to handle the receiving part is this one: https://github.com/juhovh/shairplay/issues/61#issuecomment-325887791

Maybe you can check this project and get in contact with its dev.

Hope this helps :)

**Comment by notedit** [comment]
hi  @funtax  @LionisIAm   we have solve the auth problom and make it to sdk service,  but for now we can not make it opensouce,  if anyone want commercial use, please let me know.
